### ISSUE TITLE
Example scenario

### ISSUE THREAD

**Issue by Michael1337** [featherbear/ctfd-plugin--delayed-result#1]
Hey, I like the idea, but I'm not sure in what kind of case I could use this plugin. What kind of challenge did you develop this for?

**Comment by featherbear** [comment]
Hi there! This plugin was made to support a university course, where CTFd is used as a sort of "quest board". Students are tasked to solve a challenge, and enter the results into a CTFd question.

Certain questions are brute-forceable (e.g. quantitative answers), so this plugin was made to stop students from submitting 1... 2... 3... 4... `n`. When the question is due (i.e. after a week), then only the student's latest submission will be counted

**Comment by Michael1337** [comment]
Aye, that makes sense, thanks :)
